default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: spy
  password: spy
  host: localhost # localhost'u belirtmek isteyebilirsiniz.
  port: 5432

development:
  <<: *default
  database: pisano_survey_app_development

test:
  <<: *default
  database: pisano_survey_app_test

production:
  <<: *default
  database: pisano_survey_app_production
